spring:
  application:
    name: assetman-backend

  datasource:
    url: jdbc:h2:mem:assetman;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  flyway:
    enabled: false

# Postgres config for later
#  datasource:
#    url: jdbc:postgresql://localhost:5432/assetman
#    username: assetman
#    password: assetman
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc.lob.non_contextual_creation: true
#    open-in-view: false
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "when_authorized"

assetman:
  security:
    jwt:
      secret: "CHANGE-ME-TO-A-REAL-256-BIT-SECRET-IN-PROD"
      access-token-validity-seconds: 900      # 15 minutes
      refresh-token-validity-seconds: 1209600 # 14 days

app:
  cors:
    allowed-origins: "http://localhost:4200"